---
- name: Push ruser private key
  copy:
    content: "{{ remote_ssh_passphrase_ruser_private_key }}"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0400"
  with_items:
    - "/root/.ssh/ruser"

- name: Add reverse-connect systemd service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: etc/systemd/system/reverse-connect.service.j2
      dest: /etc/systemd/system/reverse-connect.service
      mode: "0644"
    - src: usr/local/bin/reverse-connect.j2
      dest: /usr/local/bin/reverse-connect
      mode: "0700"
  notify: restart reverse-connect service

- name: Enable reverse-connect systemd services
  systemd:
    name: "reverse-connect"
    enabled: yes
