---
- name: restart reverse-connect service
  systemd:
    state: "restarted"
    daemon_reload: "yes"
    name: "{{ item }}"
  with_items:
    - reverse-connect

- name: Rebuild initramfs
  command: update-initramfs -u
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: update-grub
  command: update-grub
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
